### ISSUE TITLE
Better GBC Boot ROM

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [redacted173/sd2snes#2]
Incredible work with this, and thanks for releasing it :D

Your SNES SGB2 ROM is perfect and matches No-Intro, but you might consider switching to the more common/perfect No-Intro GBC boot ROM as well, instead of the random one that's currently used. It's:
**[BIOS] Nintendo Game Boy Color Boot ROM (World).gbc
CRC-32: 41884E46**

**Comment by redacted173** [comment]
Thanks for the suggestion, but to my knowledge the only two unmodified boot ROMS that function with Super Game Boy is the currently recommended one and the one from the SGB1 (CRC32: EC8A83B9).  This is because the SGB1 (DMG) and SGB2 (MGB) both use Super Game Boy-only hardware to send the GB header to the SNES ROM for verification during boot up.  The handhelds don't have this hardware and perform the verification and display the logo themselves.

The CGB and all other non-SGB boot ROMs don't contain this code so the ROM running on the SNES would just hang waiting for the packets.  I also see some comments on the net about the CGB bios using features new to CGB such as banked Work RAM and it's >256B.  A DMG or MGB would probably break when executing it.

As an aside, the SGB1 boot ROM will work, but the only difference is a 1 byte identification value it puts in the A register at the end.  I've seen some test ROMs mistake the $FF value from SGB2 (MGD) for CGB so they try to enable double speed mode (feature new to CGB) causing the SGB2 to hang.

**Comment by SmokeMonsterPacks** [comment]
Oh, I see. Thanks for the clarification. Keep up the great work.
