### ISSUE TITLE
Evel Knievel GBC Game - distorted characters issue

### ISSUE THREAD

**Issue by ViiMaster** [redacted173/sd2snes#22]
Hi,
First of all, thank you so much for your hard work! Now on the issue I've encountered...
On the game: Evel Knievel for the GBC which is backwards compatible, I've noticed that as soon as I reach the level selection screen, the characters appear distorted and there are general character issues with the background... I'm not sure if it is an acual hardware bug of SGB or not though... Gameplay wise the game appears fine!

**Comment by redacted173** [comment]
This game is using the OAM stat interrupt to avoid writing VRAM state when the PPU is actively reading it.  But the interrupt was missing from line 0 which caused some of the VRAM tile map writes to be dropped.  Should be fixed in the following commit:

https://github.com/redacted173/sd2snes/commit/1dfbe8769f6f0ff65a0e54202c9192c0f28ba103

I tested some other problematic games to make sure they didn't break, however I don't have time to test anything else.  It's also a relatively minor bug which doesn't warrant a new release on its own.  If you'd like to try the fix you can copy the bit file contents of the attached zip file over a sgb07 install.

[ek_missing_oam_stat_int.zip](https://github.com/redacted173/sd2snes/files/5178710/ek_missing_oam_stat_int.zip)

**Comment by ViiMaster** [comment]
Thank you very much for attending the issue! Of course I'll apply the fix since you went through the trouble of finding and correcting it! :) I understand a seperate release is not necessary for now since the core is solid as it is but it's nice that a small issue like that was corrected! Also thank you for the explanation you provided on what the problem was...

**Edit:**
Just tested it with the patch you've provided! Works great now! Thanks 👍 🥇 :)
