### ISSUE TITLE
The sound is not right, I have tested against real SGB2 and Gameboy Player

### ISSUE THREAD

**Issue by Nashismo** [redacted173/sd2snes#24]
Dear redacted173:

This thing you have done is amazing. The timing and performance is really accurate but there is one thing this SGB implementation does not do right: sound.

I use a real SGB2 on my Super Famicom and the sound is much better on the SGB2. In some games this is not noticeable, but in games like Castlevania Legends the problem is noticeable.

The problem is that the music and sounds are somewhat noisy. Is hard to describe, is like when you have an old speaker and it is simply not working right, or when you are playing music too loud on a bad speaker.

Is not crackling in the sound, it simply sounds noisy, dirty. Instead, on the same console, the SGB2 sounds great! Also I have to say that I have replaced all my capacitors in my Super Famicom so I don't see a problem there.

I wonder what could be the issue? It somehow reminded me when I had a Gameboy color and the sounds was just not right, but that was a problem with some GBC's.

Also I have tried the Gameboy Player, the same game, and it sounds even better (louder) than the SGB2 (probably because the SGB2 capacitors need changing).

So yes, that is my petition, could you check it out? I can test all you want and any help I can give, I would more than happy to help.

My best regards!
Nashismo.

**Comment by redacted173** [comment]
If I isolate the first square channel I can hear a small difference.  There is short noise around the time the frequency register changes on the game select screen and it happens on both the original SGB2 and SD2SNES.  It's more noticeable and ends more abruptly on the SD2SNES, though.  Not sure what is causing it.  If I find time I will look into it more, but that might not happen for a while.

There may be other differences.  It would help if you could find a sound effect which is easily repeatable like the noise of the whip or a specific time in a song where it happens.

The SD2SNES will never exactly match the original SGB or SGB2.  The digital logic before the downsampler can probably get a little closer assuming it doesn't require adding anything since the SD2SNES classic is full.  The downsampler and DAC are specific to the SD2SNES.

**Comment by Nashismo** [comment]
OK, I will try to record from the SGB2 an then from the SD2SNES. I will update this comment in a few days. Thank you redacted for your time.

**Comment by mrehkopf** [comment]
Which sd2snes/fxpak revision do you have? If you experience clipping artifacts it might be worth checking the SGB volume boost setting. SGB sound probably already hits full scale a lot so boosting it could easily result in clipping.

**Comment by Nashismo** [comment]
> 
> 
> Which sd2snes/fxpak revision do you have? If you experience clipping artifacts it might be worth checking the SGB volume boost setting. SGB sound probably already hits full scale a lot so boosting it could easily result in clipping.

I have the standard SD2SNES. And I use Furious firmware, I also have SGB boost OFF in the settings. Thank you anyways!

**Comment by Nashismo** [comment]
Here are the files, recorded on the same TV, same microphone (Boya M1) and same volume on TV with microphone put in same position.

In summary, it seems like the volume in the SD2SNES seems to be waving around, it is hard to describe, it just seems inconsistent.

Forgive the low volume, but in my phone sounds loud.

[record castlevania legends.zip](https://github.com/redacted173/sd2snes/files/5691221/record.castlevania.legends.zip)

**Comment by redacted173** [comment]
Thanks.  I think that's the same problem I heard when disabling all but one of the square channels on the game select screen.  It sounds as if those two channels can abruptly cut out around frequency changes.  When I get time I'll check if the output is getting clipped.  It's also possible there's a bug in the square logic or a missing register write side effect.

**Comment by Nashismo** [comment]
> 
> 
> Thanks. I think that's the same problem I heard when disabling all but one of the square channels on the game select screen. It sounds as if those two channels can abruptly cut out around frequency changes. When I get time I'll check if the output is getting clipped. It's also possible there's a bug in the square logic or a missing register write side effect.

Thank you redacted for taking the time to see this, as you can probably tell, I am very passionate about sound accuracy, in fact is the reason why I think original hardware is always best. But if FPGA is the future and it could actually replicate the SGB2, in this case, it would be simply amazing.

I am glad you could identify the problem, cheers from south america redacted. And if you need more tests, just let me know.

**Comment by redacted173** [comment]
Let me know if the attached bit files sound better.  Copy the contents of the zip file into the /sd2snes/ folder on your SD card.

It's a small code change, but a major difference in how all channel outputs and sign conversion is done.  Now an 'off' value for square and noise channels always maps to one value rather than the sign inverse of the volume.  This added back some audio popping problems from earlier releases.  The popping was fixed by doing sign conversion at the end of the channel mixing, volume, and enables so unsigned values of 0, independent of what causes it, always maps to the same signed value.

I'm a little afraid this fix unmasks another other audio bug that was hidden and will need some time to test it out.

[cvl_apu_zeroval_and_sign_conversion_1.zip](https://github.com/redacted173/sd2snes/files/5722335/cvl_apu_zeroval_and_sign_conversion_1.zip)

**Comment by Nashismo** [comment]
Thank you Redacted, I have just tested it out! And yes, it is different, it seems more stable, and yet the music still sounds a bit raw, it is hard to explain.
I guess there is no way to make it sound like the original, it would seem like in the original SGB you have some kind of filter maybe? Nonetheless I thank you for your time, I will keep my SGB for Gameboy games, and I do think the sound is good enough, actually I remember the sound on a real Gameboy wasn't that good to begin with, so it is more than OK.

Thanks again and do not trouble anymore for this issue, only if you have time and in the future release anew version, remember this posts.

**Comment by redacted173** [comment]
Hi.  It's been a long time.  I found a game, Rolan's Curse 1, where the town and outside music was very clearly getting cut on the first two channels due to a bug I originally fixed in Super Mario Land.  I fixed the bug in RC1 in the attached zip.  CVL may sound better now, but I have trouble hearing the problem.  If you have time and interest can you try these fpga files by copying them into the /sdsnes/ folder on the SD card?

If it doesn't fix the problem in Castlevania can you check if Rolan's Curse 1 music is fixed to make sure it changed?

Thanks.

[kdl2_nrx2and3_no_update_duty_pos_2.zip](https://github.com/redacted173/sd2snes/files/10154468/kdl2_nrx2and3_no_update_duty_pos_2.zip)

**Comment by redacted173** [comment]
The differences I thought I heard before seem gone with the fix so I'm going to close the issue.  If you still hear a problem please reopen or create a new issue with details.  Thanks for finding the issue.

**Comment by Nashismo** [comment]
I am sorry redacted, for some reason I did not get the notifications on my email. It should be good as last time I heard the issue was hardly perceptible. Thank you for your time Redacted!
