### ISSUE TITLE
Graphical Issue Reproducable on "Super Hunchback"

### ISSUE THREAD

**Issue by 1lluminado** [redacted173/sd2snes#26]
At the end of a main level or a bonus level, there's a loading screen with scores totaled.
The graphics present background tiles from the previous level replacing expected text.

Firmware Version: SGB07

Hardware:
SNES Jr. + SD2SNES

Conditions to Reproduce Issue:
Beat the first level of the game, the credits at the end will display graphical glitches.

Bug (SD2SNES FW SGB07)
https://streamable.com/0nvjh9
<img>https://i.imgur.com/528UO2p.png</img>

Expected (Real Super GameBoy)
https://streamable.com/73tcej
<img>https://i.imgur.com/XHgrW7E.png</img>

<>

**Comment by redacted173** [comment]
I saw a similar problem a while back on the game over screen.  VRAM writes are done during the display/rendering mode of the PPU when VRAM is not available to the CPU.  I didn't have time to look if the writes are done at the wrong time or if VRAM is supposed to be available under certain conditions.  A fix will have to wait until I have time to work on SGB again.

Thanks for the report.

**Comment by 1lluminado** [comment]
May or may not be related, but apparently that game gave the MiSTer devs some headaches as well.

https://github.com/MiSTer-devel/Gameboy_MiSTer/issues/84

**Comment by redacted173** [comment]
I looked at the bad VRAM writes on a game over screen and they are to the BG tile map.  There was a check inside a VRAM write loop to see if the updated value written of $00 matches a later read to the same address.  A data miscompare causes the same write to try again.  If the read happens during rendering the check expects a non-zero undefined value in order to detect and retry the failed write.  I changed the undefined value for VRAM and OAM from $00 to $FF and it seems to have fixed the problem in Super Hunchback.

You can try the attached bit files to see if it also fixes it for you.  Not sure if any other games rely on this undefined read behavior but it seems like a pretty safe change to make.  Most games will avoid VRAM writes during rendering and won't have the (non-atomic) read check that relies on undefined behavior to detect the race.

[sh_undefined_vram_oam_rd_value_fix.zip](https://github.com/redacted173/sd2snes/files/6292824/sh_undefined_vram_oam_rd_value_fix.zip)

**Comment by 1lluminado** [comment]
That did it!  Looks good, thanks!

https://i.imgur.com/OrcUHVW.png
