### ISSUE TITLE
SGB ui corruption

### ISSUE THREAD

**Issue by gameman733** [redacted173/sd2snes#28]
From a fresh sd2snes, I am getting some very weird SGB ui corruption when a gb game is loaded up. Half the screen is missing and everything is dark/black/red, almost like a palette issue of some sort. The SGB starts up corrupted, briefly goes to the normal game boy grey, then corrupts again once the game starts. Speaking of, the game itself runs perfectly until the system menu (l+r) is pulled up, then the palette for the game corrupts as well, but still plays normally. See below for a pic. 

https://cdn.discordapp.com/attachments/735672138433953802/829555769354485820/IMG_0795.jpg

In terms of hardware, I’m using a fairly new fxpak pro (purchased from everdrive.me in November 2020), on a standard us snes. I can check hardware revisions later if necessary, I’m just not sure where else to go with troubleshooting. The self test on the 2 files in the sd2snes firmware reports ok.

**Comment by redacted173** [comment]
That is strange.  While the SGB core and GB game can affect the border and palette, it requires an involved setup that only a small set of games use.  SML (Super Mario Land) doesn't do that.  It only does the header transfer that is part of the boot ROM startup so the BIOS verifies the checksum.  Since the game starts up that transfer worked correctly.

What version of the following are you using:
- SGB firmware version
- SD2SNES base firmware version
- BIOS file (sgb2_snes.bin) CRC or CSUM
- boot ROM (sgb2_boot.bin) CRC

One unique thing about SGB vs most other cores is the use of the analog audio pins from the cart.  Do MSU ROMs work properly on your SNES and SD2SNES?

Some things to try:
- Make sure you are running https://github.com/redacted173/sd2snes/releases/tag/sgb07 and all files in the zip replace SD2SNES firmware 1.10.3 files of the same name and have the correct file size.  Maybe try a fresh install on a different SD card.
- Try loading the SFC/SMC version of the BIOS (sgb_snes.bin) directly in the SD2SNES menu.  It won't start a GB game, but it will display the border and wait.  Check if the border colors and image are correct.
- If the border is broken try reverting all firmware files to SD2SNES 1.10.3 (no SGB support) and load the same SFC/SMC file.  If that's broken then there is something wrong with the official SD2SNES firmware loading the SNES ROM.
- Reset a few times to see if anything changes.
- Disable all features in the SD2SNES menu (region, in-game hooks, brightness patching, etc).
- Try the SGB1 BIOS and/or boot ROM.  Mix and match.  Any combination of the recommended files should print "OK" in the SD2SNES menu.

**Comment by gameman733** [comment]
Just reloaded the SD card again with a fresh sd2snes folder, with the below versions. I also moved my saves folder. Noting it, but I really doubt its related.

SGB firmware version: SGB07? SGB2? Not sure which you are asking for, release SGB07, using the SGB2 firmware. 
    SD2SNES base firmware version: 1.10.3
    BIOS file (sgb2_snes.bin) CRC or CSUM: SHA1:e5b2922ca137051059e4269b236d07a22c07bc84 (Matches readme.txt)
    boot ROM (sgb2_boot.bin) CRC: SHA1: 93407ea10d2f30ab96a314d8eca44fe160aea734 (Matches readme.txt) 

I will try MSU support (I have no reason to believe that I didn't have sound otherwise, but I can't actually say I turned the volume up to verify). I will try this again with some of your other suggestions and report back.

**Comment by gameman733** [comment]
After a lot of back and forth, I am suspecting a larger issue with either the FXPAK pro or my SNES. I am suspecting a failing PPU2 graphics chip, but I will close this issue for now until I can troubleshoot it further. Thank you for your assistance!
